- hosts: frontends
  gather_facts: false
  tasks:
  - name: Use Uri module for wrting smoke test.
    uri:
      url: "http://localhost"
      return_content: yes
    register: website

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
      msg: "Did not find 'Ansible has done its job' in page"
    when: "'Ansible has done its job' not in website.conent"
    tags:
      - aws.smoke
