---
- name: Install Load Balancer Packages
  loop: "{{ haproxy_package }}"
  package:
    name: "{{ item }}"
    state: present

- name: enable HAProxy
  service:
    name: haproxy
    enabled: yes

- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: 
    - restart haproxy